import { StyleSheet } from "react-native";
import { COLORS } from "../constants/colors";

export default StyleSheet.create({
    container:{
        padding:15
    },
    headerContainer:{
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        marginBottom:30
    },
    headerText:{
        fontSize:18,
        lineHeight:28,
        fontWeight:"700"
    },
    headerLeft:{   
       flexDirection:"row",
       justifyContent:"space-between"   
    },
    margin:{
       marginLeft:15
    },
    iconMargin:{
       marginRight:8,
       marginLeft:8
    },
    searchContainer:{
        flexDirection:"row",
        borderWidth:1,
        borderColor:"#CCC",
       borderRadius:6,
       height:40,
       alignItems:"center",  
       marginBottom:40
    },
    searchInput:{
       width:"100%"
    },
    png:{
        width:112,
        height:106,
        borderRadius:6
    },
    contentContainer:{
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
         borderWidth:1,
         padding:10,
         borderRadius:6,
         borderColor:COLORS.grey
    },
    leftContainer:{
        marginRight:5
    },
    leftHead:{
        fontSize:14,
        lineHeight:22,
        fontWeight:"700"
    },
    leftDescription:{
        fontSize:12,
        lineHeight:20,
        fontWeight:"400",
        width: "90%",
        marginTop:"5",
    },
    leftButton:{  
        borderRadius:4,
        borderWidth: 1,
        alignItems:"center",
        backgroundColor:COLORS.secondary, 
        borderColor: COLORS.primary, 
        marginTop:"15",
        width:"50%"
    },
    leftButtonText:{
      color:"black",
      paddingVertical:5,
    },
})