export enum DayOfWeek {
    MONDAY= "MONDAY",
    TUESDAY="TUESDAY",
    WEDNESDAY="WEDNESDAY",
    THIRSDAY="THIRSDAY",
    FRIDAY="FRIDAY",
    SATURDAY="SATURDAY",
    SUNDAY="SUNDAY"
}

export enum Role {
    ADMMIN="ADMIN",
    DOCTOR="DOCTOR",
    NURSE="NURSE",
    FRONTDESK="FRONTDESK"
}